CC     = gcc-14
CC     = clang-20
CFLAGS = -g
CFLAGS = -O3 -march=native
#FTR_GLUT=1
all : default ftr #misc
ENABLE_PNG  = 1
ENABLE_TIFF = 1
ENABLE_JPEG = 1
ENABLE_PGSL = 1
ENABLE_WEBP = 1
#ENABLE_HEIF = 1
#ENABLE_HDF5 = 1
include Makefile

# this is an example of makefile configuration
